# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off
from __future__ import annotations

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template actions.py.jinja --
from typing import TypeVar
import warnings

from . import types, errors, bases
from ._compat import model_parse
from ._constants import CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED

if TYPE_CHECKING:
    from .client import Prisma
    from .bases import _PrismaModel


_PrismaModelT = TypeVar('_PrismaModelT', bound='_PrismaModel')


class IngestionLogsActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.IngestionLogs]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await IngestionLogs.prisma().query_raw(
            'SELECT * FROM IngestionLogs WHERE id = $1',
            1103527590,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.IngestionLogs
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await IngestionLogs.prisma().query_first(
            'SELECT * FROM IngestionLogs WHERE job_id = $1',
            'dhheabfhf',
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.IngestionLogsCreateInput,
        include: Optional[types.IngestionLogsInclude] = None
    ) -> _PrismaModelT:
        """Create a new IngestionLogs record.

        Parameters
        ----------
        data
            IngestionLogs record data
        include
            Specifies which relations should be loaded on the returned IngestionLogs model

        Returns
        -------
        prisma.models.IngestionLogs
            The created IngestionLogs record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a IngestionLogs record from just the required fields
        ingestionlogs = await IngestionLogs.prisma().create(
            data={
                # data to create a IngestionLogs record
                'job_id': 'ggciceaie',
                'log_type': 'bbehjachib',
                'message': 'cadfabfehe',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.IngestionLogsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple IngestionLogs records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of IngestionLogs record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await IngestionLogs.prisma().create_many(
            data=[
                {
                    # data to create a IngestionLogs record
                    'job_id': 'dgiiaaijj',
                    'log_type': 'bfaiacjjfc',
                    'message': 'eigcfgbif',
                },
                {
                    # data to create a IngestionLogs record
                    'job_id': 'bagcfbhiig',
                    'log_type': 'cghideieh',
                    'message': 'biabhbdai',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.IngestionLogsWhereUniqueInput,
        include: Optional[types.IngestionLogsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single IngestionLogs record.

        Parameters
        ----------
        where
            IngestionLogs filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned IngestionLogs model

        Returns
        -------
        prisma.models.IngestionLogs
            The deleted IngestionLogs record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        ingestionlogs = await IngestionLogs.prisma().delete(
            where={
                'id': 836760821,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.IngestionLogsWhereUniqueInput,
        include: Optional[types.IngestionLogsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique IngestionLogs record.

        Parameters
        ----------
        where
            IngestionLogs filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned IngestionLogs model

        Returns
        -------
        prisma.models.IngestionLogs
            The found IngestionLogs record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        ingestionlogs = await IngestionLogs.prisma().find_unique(
            where={
                'id': 595337866,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.IngestionLogsWhereUniqueInput,
        include: Optional[types.IngestionLogsInclude] = None
    ) -> _PrismaModelT:
        """Find a unique IngestionLogs record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            IngestionLogs filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned IngestionLogs model

        Returns
        -------
        prisma.models.IngestionLogs
            The found IngestionLogs record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        ingestionlogs = await IngestionLogs.prisma().find_unique_or_raise(
            where={
                'id': 790425851,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.IngestionLogsWhereInput] = None,
        cursor: Optional[types.IngestionLogsWhereUniqueInput] = None,
        include: Optional[types.IngestionLogsInclude] = None,
        order: Optional[Union[types.IngestionLogsOrderByInput, List[types.IngestionLogsOrderByInput]]] = None,
        distinct: Optional[List[types.IngestionLogsScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple IngestionLogs records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of IngestionLogs records returned
        skip
            Ignore the first N results
        where
            IngestionLogs filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned IngestionLogs model
        order
            Order the returned IngestionLogs records by any field
        distinct
            Filter IngestionLogs records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.IngestionLogs]
            The list of all IngestionLogs records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 IngestionLogs records
        ingestionlogs = await IngestionLogs.prisma().find_many(take=10)

        # find the first 5 IngestionLogs records ordered by the log_type field
        ingestionlogs = await IngestionLogs.prisma().find_many(
            take=5,
            order={
                'log_type': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.IngestionLogsWhereInput] = None,
        cursor: Optional[types.IngestionLogsWhereUniqueInput] = None,
        include: Optional[types.IngestionLogsInclude] = None,
        order: Optional[Union[types.IngestionLogsOrderByInput, List[types.IngestionLogsOrderByInput]]] = None,
        distinct: Optional[List[types.IngestionLogsScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single IngestionLogs record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            IngestionLogs filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned IngestionLogs model
        order
            Order the returned IngestionLogs records by any field
        distinct
            Filter IngestionLogs records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.IngestionLogs
            The first IngestionLogs record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second IngestionLogs record ordered by the message field
        ingestionlogs = await IngestionLogs.prisma().find_first(
            skip=1,
            order={
                'message': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.IngestionLogsWhereInput] = None,
        cursor: Optional[types.IngestionLogsWhereUniqueInput] = None,
        include: Optional[types.IngestionLogsInclude] = None,
        order: Optional[Union[types.IngestionLogsOrderByInput, List[types.IngestionLogsOrderByInput]]] = None,
        distinct: Optional[List[types.IngestionLogsScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single IngestionLogs record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            IngestionLogs filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned IngestionLogs model
        order
            Order the returned IngestionLogs records by any field
        distinct
            Filter IngestionLogs records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.IngestionLogs
            The first IngestionLogs record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second IngestionLogs record ordered by the timestamp field
        ingestionlogs = await IngestionLogs.prisma().find_first_or_raise(
            skip=1,
            order={
                'timestamp': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.IngestionLogsUpdateInput,
        where: types.IngestionLogsWhereUniqueInput,
        include: Optional[types.IngestionLogsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single IngestionLogs record.

        Parameters
        ----------
        data
            IngestionLogs record data specifying what to update
        where
            IngestionLogs filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned IngestionLogs model

        Returns
        -------
        prisma.models.IngestionLogs
            The updated IngestionLogs record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        ingestionlogs = await IngestionLogs.prisma().update(
            where={
                'id': 2111915288,
            },
            data={
                # data to update the IngestionLogs record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.IngestionLogsWhereUniqueInput,
        data: types.IngestionLogsUpsertInput,
        include: Optional[types.IngestionLogsInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            IngestionLogs filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned IngestionLogs model

        Returns
        -------
        prisma.models.IngestionLogs
            The created or updated IngestionLogs record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        ingestionlogs = await IngestionLogs.prisma().upsert(
            where={
                'id': 1149758321,
            },
            data={
                'create': {
                    'id': 1149758321,
                    'job_id': 'bagcfbhiig',
                    'log_type': 'cghideieh',
                    'message': 'biabhbdai',
                },
                'update': {
                    'job_id': 'bagcfbhiig',
                    'log_type': 'cghideieh',
                    'message': 'biabhbdai',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.IngestionLogsUpdateManyMutationInput,
        where: types.IngestionLogsWhereInput,
    ) -> int:
        """Update multiple IngestionLogs records

        Parameters
        ----------
        data
            IngestionLogs data to update the selected IngestionLogs records to
        where
            Filter to select the IngestionLogs records to update

        Returns
        -------
        int
            The total number of IngestionLogs records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all IngestionLogs records
        total = await IngestionLogs.prisma().update_many(
            data={
                'id': 1644289366
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.IngestionLogsWhereInput] = None,
        cursor: Optional[types.IngestionLogsWhereUniqueInput] = None,
    ) -> int:
        """Count the number of IngestionLogs records present in the database

        Parameters
        ----------
        select
            Select the IngestionLogs fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            IngestionLogs filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.IngestionLogsCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await IngestionLogs.prisma().count()

        # results: prisma.types.IngestionLogsCountAggregateOutput
        results = await IngestionLogs.prisma().count(
            select={
                '_all': True,
                'job_id': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.IngestionLogsCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.IngestionLogsWhereInput] = None,
        cursor: Optional[types.IngestionLogsWhereUniqueInput] = None,
    ) -> types.IngestionLogsCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.IngestionLogsCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.IngestionLogsWhereInput] = None,
        cursor: Optional[types.IngestionLogsWhereUniqueInput] = None,
    ) -> Union[int, types.IngestionLogsCountAggregateOutput]:
        """Count the number of IngestionLogs records present in the database

        Parameters
        ----------
        select
            Select the IngestionLogs fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            IngestionLogs filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.IngestionLogsCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await IngestionLogs.prisma().count()

        # results: prisma.types.IngestionLogsCountAggregateOutput
        results = await IngestionLogs.prisma().count(
            select={
                '_all': True,
                'log_type': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.IngestionLogsCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.IngestionLogsWhereInput] = None
    ) -> int:
        """Delete multiple IngestionLogs records.

        Parameters
        ----------
        where
            Optional IngestionLogs filter to find the records to be deleted

        Returns
        -------
        int
            The total number of IngestionLogs records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all IngestionLogs records
        total = await IngestionLogs.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.IngestionLogsScalarFieldKeysT'],
        *,
        where: Optional['types.IngestionLogsWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.IngestionLogsAvgAggregateInput'] = None,
        sum: Optional['types.IngestionLogsSumAggregateInput'] = None,
        min: Optional['types.IngestionLogsMinAggregateInput'] = None,
        max: Optional['types.IngestionLogsMaxAggregateInput'] = None,
        having: Optional['types.IngestionLogsScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.IngestionLogsCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.IngestionLogsScalarFieldKeysT', 'types.SortOrder'], List[Mapping['types.IngestionLogsScalarFieldKeysT', 'types.SortOrder']]]] = None,
    ) -> List['types.IngestionLogsGroupByOutput']:
        """Group IngestionLogs records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar IngestionLogs fields to group records by
        where
            IngestionLogs filter to select records
        take
            Limit the maximum number of IngestionLogs records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.IngestionLogsGroupByOutput]
            A list of dictionaries representing the IngestionLogs record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group IngestionLogs records by message values
        # and count how many records are in each group
        results = await IngestionLogs.prisma().group_by(
            ['message'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]


class BankTransactionsActions(Generic[_PrismaModelT]):
    __slots__ = (
        '_client',
        '_model',
    )

    def __init__(self, client: Prisma, model: Type[_PrismaModelT]) -> None:
        self._client = client
        self._model = model

    async def query_raw(
        self,
        query: LiteralString,
        *args: Any,
    ) -> List[_PrismaModelT]:
        """Execute a raw SQL query

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        List[prisma.models.BankTransactions]
            The records returned by the SQL query

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        users = await BankTransactions.prisma().query_raw(
            'SELECT * FROM BankTransactions WHERE id = $1',
            1388290519,
        )
        ```
        """
        return await self._client.query_raw(query, *args, model=self._model)

    async def query_first(
        self,
        query: LiteralString,
        *args: Any,
    ) -> Optional[_PrismaModelT]:
        """Execute a raw SQL query, returning the first result

        Parameters
        ----------
        query
            The raw SQL query string to be executed
        *args
            Parameters to be passed to the SQL query, these MUST be used over
            string formatting to avoid an SQL injection vulnerability

        Returns
        -------
        prisma.models.BankTransactions
            The first record returned by the SQL query
        None
            The raw SQL query did not return any records

        Raises
        ------
        prisma_errors.RawQueryError
            This could be due to invalid syntax, mismatched number of parameters or any other error
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        user = await BankTransactions.prisma().query_first(
            'SELECT * FROM BankTransactions WHERE transaction_date = $1',
            datetime.datetime.utcnow(),
        )
        ```
        """
        return await self._client.query_first(query, *args, model=self._model)

    async def create(
        self,
        data: types.BankTransactionsCreateInput,
        include: Optional[types.BankTransactionsInclude] = None
    ) -> _PrismaModelT:
        """Create a new BankTransactions record.

        Parameters
        ----------
        data
            BankTransactions record data
        include
            Specifies which relations should be loaded on the returned BankTransactions model

        Returns
        -------
        prisma.models.BankTransactions
            The created BankTransactions record

        Raises
        ------
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # create a BankTransactions record from just the required fields
        banktransactions = await BankTransactions.prisma().create(
            data={
                # data to create a BankTransactions record
                'type': 'bgehebiafc',
                'amount_decimal': Decimal('1675546029.176727'),
                'raw_history_text': 'dcgchcbbf',
                'source_file_name': 'bdedcabahc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='create',
            model=self._model,
            arguments={
                'data': data,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def create_many(
        self,
        data: List[types.BankTransactionsCreateWithoutRelationsInput],
        *,
        skip_duplicates: Optional[bool] = None,
    ) -> int:
        """Create multiple BankTransactions records at once.

        This function is *not* available when using SQLite.

        Parameters
        ----------
        data
            List of BankTransactions record data
        skip_duplicates
            Boolean flag for ignoring unique constraint errors

        Returns
        -------
        int
            The total number of records created

        Raises
        ------
        prisma.errors.UnsupportedDatabaseError
            Attempting to query when using SQLite
        prisma.errors.UniqueViolationError
            A unique constraint check has failed, these can be ignored with the `skip_duplicates` argument
        prisma.errors.MissingRequiredValueError
            Value is required but was not found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        total = await BankTransactions.prisma().create_many(
            data=[
                {
                    # data to create a BankTransactions record
                    'type': 'ghfhiafcb',
                    'amount_decimal': Decimal('744964398.196968'),
                    'raw_history_text': 'bbbgbhfjge',
                    'source_file_name': 'igbehcbab',
                },
                {
                    # data to create a BankTransactions record
                    'type': 'bdadaadhag',
                    'amount_decimal': Decimal('1686638315.200043'),
                    'raw_history_text': 'bigibebcib',
                    'source_file_name': 'bigaiehgcc',
                },
            ],
            skip_duplicates=True,
        )
        ```
        """
        if skip_duplicates and self._client._active_provider in CREATE_MANY_SKIP_DUPLICATES_UNSUPPORTED:
            raise errors.UnsupportedDatabaseError(self._client._active_provider, 'create_many_skip_duplicates')

        resp = await self._client._execute(
            method='create_many',
            model=self._model,
            arguments={
                'data': data,
                'skipDuplicates': skip_duplicates,
            },
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    async def delete(
        self,
        where: types.BankTransactionsWhereUniqueInput,
        include: Optional[types.BankTransactionsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Delete a single BankTransactions record.

        Parameters
        ----------
        where
            BankTransactions filter to select the record to be deleted, must be unique
        include
            Specifies which relations should be loaded on the returned BankTransactions model

        Returns
        -------
        prisma.models.BankTransactions
            The deleted BankTransactions record
        None
            Could not find a record to delete

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        banktransactions = await BankTransactions.prisma().delete(
            where={
                'id': 1448521415,
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='delete',
                model=self._model,
                arguments={
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def find_unique(
        self,
        where: types.BankTransactionsWhereUniqueInput,
        include: Optional[types.BankTransactionsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Find a unique BankTransactions record.

        Parameters
        ----------
        where
            BankTransactions filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned BankTransactions model

        Returns
        -------
        prisma.models.BankTransactions
            The found BankTransactions record
        None
            No record matching the given input could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        banktransactions = await BankTransactions.prisma().find_unique(
            where={
                'id': 1628650740,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None
        return model_parse(self._model, result)

    async def find_unique_or_raise(
        self,
        where: types.BankTransactionsWhereUniqueInput,
        include: Optional[types.BankTransactionsInclude] = None
    ) -> _PrismaModelT:
        """Find a unique BankTransactions record. Raises `RecordNotFoundError` if no record is found.

        Parameters
        ----------
        where
            BankTransactions filter to find the record, must be unique
        include
            Specifies which relations should be loaded on the returned BankTransactions model

        Returns
        -------
        prisma.models.BankTransactions
            The found BankTransactions record

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        banktransactions = await BankTransactions.prisma().find_unique_or_raise(
            where={
                'id': 1249606685,
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_unique_or_raise',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def find_many(
        self,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.BankTransactionsWhereInput] = None,
        cursor: Optional[types.BankTransactionsWhereUniqueInput] = None,
        include: Optional[types.BankTransactionsInclude] = None,
        order: Optional[Union[types.BankTransactionsOrderByInput, List[types.BankTransactionsOrderByInput]]] = None,
        distinct: Optional[List[types.BankTransactionsScalarFieldKeys]] = None,
    ) -> List[_PrismaModelT]:
        """Find multiple BankTransactions records.

        An empty list is returned if no records could be found.

        Parameters
        ----------
        take
            Limit the maximum number of BankTransactions records returned
        skip
            Ignore the first N results
        where
            BankTransactions filter to select records
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned BankTransactions model
        order
            Order the returned BankTransactions records by any field
        distinct
            Filter BankTransactions records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        List[prisma.models.BankTransactions]
            The list of all BankTransactions records that could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the first 10 BankTransactions records
        banktransactions = await BankTransactions.prisma().find_many(take=10)

        # find the first 5 BankTransactions records ordered by the posting_date field
        banktransactions = await BankTransactions.prisma().find_many(
            take=5,
            order={
                'posting_date': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_many',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return [model_parse(self._model, r) for r in resp['data']['result']]

    async def find_first(
        self,
        skip: Optional[int] = None,
        where: Optional[types.BankTransactionsWhereInput] = None,
        cursor: Optional[types.BankTransactionsWhereUniqueInput] = None,
        include: Optional[types.BankTransactionsInclude] = None,
        order: Optional[Union[types.BankTransactionsOrderByInput, List[types.BankTransactionsOrderByInput]]] = None,
        distinct: Optional[List[types.BankTransactionsScalarFieldKeys]] = None,
    ) -> Optional[_PrismaModelT]:
        """Find a single BankTransactions record.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            BankTransactions filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned BankTransactions model
        order
            Order the returned BankTransactions records by any field
        distinct
            Filter BankTransactions records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.BankTransactions
            The first BankTransactions record found, matching the given arguments
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second BankTransactions record ordered by the type field
        banktransactions = await BankTransactions.prisma().find_first(
            skip=1,
            order={
                'type': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        result = resp['data']['result']
        if result is None:
            return None

        return model_parse(self._model, result)

    async def find_first_or_raise(
        self,
        skip: Optional[int] = None,
        where: Optional[types.BankTransactionsWhereInput] = None,
        cursor: Optional[types.BankTransactionsWhereUniqueInput] = None,
        include: Optional[types.BankTransactionsInclude] = None,
        order: Optional[Union[types.BankTransactionsOrderByInput, List[types.BankTransactionsOrderByInput]]] = None,
        distinct: Optional[List[types.BankTransactionsScalarFieldKeys]] = None,
    ) -> _PrismaModelT:
        """Find a single BankTransactions record. Raises `RecordNotFoundError` if no record was found.

        Parameters
        ----------
        skip
            Ignore the first N records
        where
            BankTransactions filter to select the record
        cursor
            Specifies the position in the list to start returning results from, (typically an ID field)
        include
            Specifies which relations should be loaded on the returned BankTransactions model
        order
            Order the returned BankTransactions records by any field
        distinct
            Filter BankTransactions records by either a single distinct field or distinct combinations of fields

        Returns
        -------
        prisma.models.BankTransactions
            The first BankTransactions record found, matching the given arguments

        Raises
        ------
        prisma.errors.RecordNotFoundError
            No record was found
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # find the second BankTransactions record ordered by the amount_decimal field
        banktransactions = await BankTransactions.prisma().find_first_or_raise(
            skip=1,
            order={
                'amount_decimal': 'desc',
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='find_first_or_raise',
            model=self._model,
            arguments={
                'skip': skip,
                'where': where,
                'order_by': order,
                'cursor': cursor,
                'include': include,
                'distinct': distinct,
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update(
        self,
        data: types.BankTransactionsUpdateInput,
        where: types.BankTransactionsWhereUniqueInput,
        include: Optional[types.BankTransactionsInclude] = None
    ) -> Optional[_PrismaModelT]:
        """Update a single BankTransactions record.

        Parameters
        ----------
        data
            BankTransactions record data specifying what to update
        where
            BankTransactions filter to select the unique record to create / update
        include
            Specifies which relations should be loaded on the returned BankTransactions model

        Returns
        -------
        prisma.models.BankTransactions
            The updated BankTransactions record
        None
            No record could be found

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        banktransactions = await BankTransactions.prisma().update(
            where={
                'id': 835903122,
            },
            data={
                # data to update the BankTransactions record to
            },
        )
        ```
        """
        try:
            resp = await self._client._execute(
                method='update',
                model=self._model,
                arguments={
                    'data': data,
                    'where': where,
                    'include': include,
                },
            )
        except errors.RecordNotFoundError:
            return None

        return model_parse(self._model, resp['data']['result'])

    async def upsert(
        self,
        where: types.BankTransactionsWhereUniqueInput,
        data: types.BankTransactionsUpsertInput,
        include: Optional[types.BankTransactionsInclude] = None,
    ) -> _PrismaModelT:
        """Updates an existing record or create a new one

        Parameters
        ----------
        where
            BankTransactions filter to select the unique record to create / update
        data
            Data specifying what fields to set on create and update
        include
            Specifies which relations should be loaded on the returned BankTransactions model

        Returns
        -------
        prisma.models.BankTransactions
            The created or updated BankTransactions record

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python
        prisma.errors.MissingRequiredValueError
            Value is required but was not found

        Example
        -------
        ```py
        banktransactions = await BankTransactions.prisma().upsert(
            where={
                'id': 763719779,
            },
            data={
                'create': {
                    'id': 763719779,
                    'type': 'bdadaadhag',
                    'amount_decimal': Decimal('1686638315.200043'),
                    'raw_history_text': 'bigibebcib',
                    'source_file_name': 'bigaiehgcc',
                },
                'update': {
                    'type': 'bdadaadhag',
                    'amount_decimal': Decimal('1686638315.200043'),
                    'raw_history_text': 'bigibebcib',
                    'source_file_name': 'bigaiehgcc',
                },
            },
        )
        ```
        """
        resp = await self._client._execute(
            method='upsert',
            model=self._model,
            arguments={
                'where': where,
                'include': include,
                'create': data.get('create'),
                'update': data.get('update'),
            },
        )
        return model_parse(self._model, resp['data']['result'])

    async def update_many(
        self,
        data: types.BankTransactionsUpdateManyMutationInput,
        where: types.BankTransactionsWhereInput,
    ) -> int:
        """Update multiple BankTransactions records

        Parameters
        ----------
        data
            BankTransactions data to update the selected BankTransactions records to
        where
            Filter to select the BankTransactions records to update

        Returns
        -------
        int
            The total number of BankTransactions records that were updated

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # update all BankTransactions records
        total = await BankTransactions.prisma().update_many(
            data={
                'raw_history_text': 'ecjjjfbae'
            },
            where={}
        )
        ```
        """
        resp = await self._client._execute(
            method='update_many',
            model=self._model,
            arguments={'data': data, 'where': where,},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    @overload
    async def count(
        self,
        select: None = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.BankTransactionsWhereInput] = None,
        cursor: Optional[types.BankTransactionsWhereUniqueInput] = None,
    ) -> int:
        """Count the number of BankTransactions records present in the database

        Parameters
        ----------
        select
            Select the BankTransactions fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            BankTransactions filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.BankTransactionsCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await BankTransactions.prisma().count()

        # results: prisma.types.BankTransactionsCountAggregateOutput
        results = await BankTransactions.prisma().count(
            select={
                '_all': True,
                'raw_value_text': True,
            },
        )
        ```
        """


    @overload
    async def count(
        self,
        select: types.BankTransactionsCountAggregateInput,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.BankTransactionsWhereInput] = None,
        cursor: Optional[types.BankTransactionsWhereUniqueInput] = None,
    ) -> types.BankTransactionsCountAggregateOutput:
        ...

    async def count(
        self,
        select: Optional[types.BankTransactionsCountAggregateInput] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        where: Optional[types.BankTransactionsWhereInput] = None,
        cursor: Optional[types.BankTransactionsWhereUniqueInput] = None,
    ) -> Union[int, types.BankTransactionsCountAggregateOutput]:
        """Count the number of BankTransactions records present in the database

        Parameters
        ----------
        select
            Select the BankTransactions fields to be counted
        take
            Limit the maximum result
        skip
            Ignore the first N records
        where
            BankTransactions filter to find records
        cursor
            Specifies the position in the list to start counting results from, (typically an ID field)
        order
            This parameter is deprecated and will be removed in a future release

        Returns
        -------
        int
            The total number of records found, returned if `select` is not given

        prisma.types.BankTransactionsCountAggregateOutput
            Data returned when `select` is used, the fields present in this dictionary will
            match the fields passed in the `select` argument

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # total: int
        total = await BankTransactions.prisma().count()

        # results: prisma.types.BankTransactionsCountAggregateOutput
        results = await BankTransactions.prisma().count(
            select={
                '_all': True,
                'raw_balance_text': True,
            },
        )
        ```
        """

        # TODO: this selection building should be moved to the QueryBuilder
        #
        # note the distinction between checking for `not select` here and `select is None`
        # later is to handle the case that the given select dictionary is empty, this
        # is a limitation of our types.
        if not select:
            root_selection = ['_count { _all }']
        else:

            root_selection = [
                '_count {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))
            ]

        resp = await self._client._execute(
            method='count',
            model=self._model,
            arguments={
                'take': take,
                'skip': skip,
                'where': where,
                'cursor': cursor,
            },
            root_selection=root_selection,
        )

        if select is None:
            return cast(int, resp['data']['result']['_count']['_all'])
        else:
            return cast(types.BankTransactionsCountAggregateOutput, resp['data']['result']['_count'])

    async def delete_many(
        self,
        where: Optional[types.BankTransactionsWhereInput] = None
    ) -> int:
        """Delete multiple BankTransactions records.

        Parameters
        ----------
        where
            Optional BankTransactions filter to find the records to be deleted

        Returns
        -------
        int
            The total number of BankTransactions records that were deleted

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # delete all BankTransactions records
        total = await BankTransactions.prisma().delete_many()
        ```
        """
        resp = await self._client._execute(
            method='delete_many',
            model=self._model,
            arguments={'where': where},
            root_selection=['count'],
        )
        return int(resp['data']['result']['count'])

    # TODO: make this easier to work with safely, currently output fields are typed as
    #       not required, we should refactor the return type
    # TODO: consider returning a Dict where the keys are a Tuple of the `by` selection
    # TODO: statically type that the order argument is required when take or skip are present
    async def group_by(
        self,
        by: List['types.BankTransactionsScalarFieldKeysT'],
        *,
        where: Optional['types.BankTransactionsWhereInput'] = None,
        take: Optional[int] = None,
        skip: Optional[int] = None,
        avg: Optional['types.BankTransactionsAvgAggregateInput'] = None,
        sum: Optional['types.BankTransactionsSumAggregateInput'] = None,
        min: Optional['types.BankTransactionsMinAggregateInput'] = None,
        max: Optional['types.BankTransactionsMaxAggregateInput'] = None,
        having: Optional['types.BankTransactionsScalarWhereWithAggregatesInput'] = None,
        count: Optional[Union[bool, 'types.BankTransactionsCountAggregateInput']] = None,
        order: Optional[Union[Mapping['types.BankTransactionsScalarFieldKeysT', 'types.SortOrder'], List[Mapping['types.BankTransactionsScalarFieldKeysT', 'types.SortOrder']]]] = None,
    ) -> List['types.BankTransactionsGroupByOutput']:
        """Group BankTransactions records by one or more field values and perform aggregations
        each group such as finding the average.

        Parameters
        ----------
        by
            List of scalar BankTransactions fields to group records by
        where
            BankTransactions filter to select records
        take
            Limit the maximum number of BankTransactions records returned
        skip
            Ignore the first N records
        avg
            Adds the average of all values of the specified fields to the `_avg` field
            in the returned data.
        sum
            Adds the sum of all values of the specified fields to the `_sum` field
            in the returned data.
        min
            Adds the smallest available value for the specified fields to the `_min` field
            in the returned data.
        max
            Adds the largest available value for the specified fields to the `_max` field
            in the returned data.
        count
            Adds a count of non-fields to the `_count` field in the returned data.
        having
            Allows you to filter groups by an aggregate value - for example only return
            groups having an average age less than 50.
        order
            Lets you order the returned list by any property that is also present in `by`.
            Only **one** field is allowed at a time.

        Returns
        -------
        List[prisma.types.BankTransactionsGroupByOutput]
            A list of dictionaries representing the BankTransactions record,
            this will also have additional fields present if aggregation arguments
            are used (see the above parameters)

        Raises
        ------
        prisma.errors.PrismaError
            Catch all for every exception raised by Prisma Client Python

        Example
        -------
        ```py
        # group BankTransactions records by source_file_name values
        # and count how many records are in each group
        results = await BankTransactions.prisma().group_by(
            ['source_file_name'],
            count=True,
        )
        ```
        """
        if order is None:
            if take is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'take\' is present')

            if skip is not None:
                raise TypeError('Missing argument: \'order\' which is required when \'skip\' is present')

        root_selection: List[str] = [*by]
        if avg is not None:
            root_selection.append(_select_fields('_avg', avg))

        if min is not None:
            root_selection.append(_select_fields('_min', min))

        if sum is not None:
            root_selection.append(_select_fields('_sum', sum))

        if max is not None:
            root_selection.append(_select_fields('_max', max))

        if count is not None:
            if count is True:
                root_selection.append('_count { _all }')
            elif isinstance(count, dict):
                root_selection.append(_select_fields('_count', count))

        resp = await self._client._execute(
            method='group_by',
            model=self._model,
            arguments={
                'by': by,
                'take': take,
                'skip': skip,
                'where': where,
                'having': having,
                'orderBy': order,
            },
            root_selection=root_selection,
        )
        return resp['data']['result']  # type: ignore[no-any-return]



def _select_fields(root: str, select: Mapping[str, Any]) -> str:
    """Helper to build a GraphQL selection string

    This is a work around until field selection is added to the query builder.
    """

    return root + ' {{ {0} }}'.format(' '.join(k for k, v in select.items() if v is True))


from . import models