# -*- coding: utf-8 -*-
# code generated by Prisma. DO NOT EDIT.
# pyright: reportUnusedImport=false
# fmt: off

# global imports for type checking
from builtins import bool as _bool
from builtins import int as _int
from builtins import float as _float
from builtins import str as _str
import sys
import decimal
import datetime
from typing import (
    TYPE_CHECKING,
    Optional,
    Iterable,
    Iterator,
    Sequence,
    Callable,
    ClassVar,
    NoReturn,
    TypeVar,
    Generic,
    Mapping,
    Tuple,
    Union,
    List,
    Dict,
    Type,
    Any,
    Set,
    overload,
    cast,
)
from typing_extensions import TypedDict, Literal


from typing_extensions import LiteralString
# -- template types.py.jinja --
from typing import TypeVar

import httpx
from . import _types
from .utils import _NoneType



# TODO: filters with aggregates should have their own recursive fields
# TODO: cleanup whitespace control
# TODO: add an argument to signify that the last iteration should be skipped


SortMode = _types.SortMode
SortOrder = _types.SortOrder

MetricsFormat = _types.MetricsFormat

DatasourceOverride = _types.DatasourceOverride
HttpConfig = _types.HttpConfig


# types that can be serialized to json by our query builder
Serializable = Union[
    None,
    bool,
    float,
    int,
    str,
    datetime.datetime,
    List['Serializable'],
    Dict[None, 'Serializable'],
    Dict[bool, 'Serializable'],
    Dict[float, 'Serializable'],
    Dict[int, 'Serializable'],
    Dict[str, 'Serializable'],
]


StringFilter = TypedDict(
    'StringFilter',
    {
        'equals': str,
        'not_in': List[str],
        'lt': str,
        'lte': str,
        'gt': str,
        'gte': str,
        'contains': str,
        'startswith': str,
        'endswith': str,
        'in': List[str],
        'not': Union[str, 'StringFilter'],
        'mode': SortMode,
        'search': str,
    },
    total=False,
)



class StringWithAggregatesFilter(StringFilter, total=False):
    _max: 'StringFilter'
    _min: 'StringFilter'
    _sum: 'StringFilter'
    _avg: 'StringFilter'
    _count: 'IntFilter'


DateTimeFilter = TypedDict(
    'DateTimeFilter',
    {
        'equals': datetime.datetime,
        'not_in': List[datetime.datetime],
        'lt': datetime.datetime,
        'lte': datetime.datetime,
        'gt': datetime.datetime,
        'gte': datetime.datetime,
        'in': List[datetime.datetime],
        'not': Union[datetime.datetime, 'DateTimeFilter'],
    },
    total=False,
)



class DateTimeWithAggregatesFilter(DateTimeFilter, total=False):
    _max: 'DateTimeFilter'
    _min: 'DateTimeFilter'
    _sum: 'DateTimeFilter'
    _avg: 'DateTimeFilter'
    _count: 'IntFilter'


BooleanFilter = TypedDict(
    'BooleanFilter',
    {
        'equals': bool,
        'not': Union[bool, 'BooleanFilter'],
    },
    total=False,
)



class BooleanWithAggregatesFilter(BooleanFilter, total=False):
    _max: 'BooleanFilter'
    _min: 'BooleanFilter'
    _sum: 'BooleanFilter'
    _avg: 'BooleanFilter'
    _count: 'IntFilter'


IntFilter = TypedDict(
    'IntFilter',
    {
        'equals': int,
        'not_in': List[int],
        'lt': int,
        'lte': int,
        'gt': int,
        'gte': int,
        'in': List[int],
        'not': Union[int, 'IntFilter'],
    },
    total=False,
)



class IntWithAggregatesFilter(IntFilter, total=False):
    _max: 'IntFilter'
    _min: 'IntFilter'
    _sum: 'IntFilter'
    _avg: 'IntFilter'
    _count: 'IntFilter'


BigIntFilter = IntFilter
BigIntWithAggregatesFilter = IntWithAggregatesFilter
FloatFilter = TypedDict(
    'FloatFilter',
    {
        'equals': float,
        'not_in': List[float],
        'lt': float,
        'lte': float,
        'gt': float,
        'gte': float,
        'in': List[float],
        'not': Union[float, 'FloatFilter'],
    },
    total=False,
)



class FloatWithAggregatesFilter(FloatFilter, total=False):
    _max: 'FloatFilter'
    _min: 'FloatFilter'
    _sum: 'FloatFilter'
    _avg: 'FloatFilter'
    _count: 'IntFilter'


BytesFilter = TypedDict(
    'BytesFilter',
    {
        'equals': 'fields.Base64',
        'in': List['fields.Base64'],
        'not_in': List['fields.Base64'],
        'not': Union['fields.Base64', 'BytesFilter'],
    },
    total=False,
)



class BytesWithAggregatesFilter(BytesFilter, total=False):
    _max: 'BytesFilter'
    _min: 'BytesFilter'
    _sum: 'BytesFilter'
    _avg: 'BytesFilter'
    _count: 'IntFilter'


# TODO: preview feature for improving JSON filtering
JsonFilter = TypedDict(
    'JsonFilter',
    {
        'equals': 'fields.Json',
        'not': 'fields.Json',
    },
    total=False,
)


class JsonWithAggregatesFilter(JsonFilter, total=False):
    _max: 'JsonFilter'
    _min: 'JsonFilter'
    _sum: 'JsonFilter'
    _avg: 'JsonFilter'
    _count: 'IntFilter'


DecimalFilter = TypedDict(
    'DecimalFilter',
    {
        'equals': decimal.Decimal,
        'not_in': List[decimal.Decimal],
        'lt': decimal.Decimal,
        'lte': decimal.Decimal,
        'gt': decimal.Decimal,
        'gte': decimal.Decimal,
        'in': List[decimal.Decimal],
        'not': Union[decimal.Decimal, 'DecimalFilter'],
    },
    total=False,
)



class DecimalWithAggregatesFilter(StringFilter, total=False):
    _max: 'DecimalFilter'
    _min: 'DecimalFilter'
    _sum: 'DecimalFilter'
    _avg: 'DecimalFilter'
    _count: 'IntFilter'


class _FloatSetInput(TypedDict):
    set: float


class _FloatDivideInput(TypedDict):
    divide: float


class _FloatMultiplyInput(TypedDict):
    multiply: float


class _FloatIncrementInput(TypedDict):
    increment: float


class _FloatDecrementInput(TypedDict):
    decrement: float


class _IntSetInput(TypedDict):
    set: int


class _IntDivideInput(TypedDict):
    divide: int


class _IntMultiplyInput(TypedDict):
    multiply: int


class _IntIncrementInput(TypedDict):
    increment: int


class _IntDecrementInput(TypedDict):
    decrement: int


AtomicFloatInput = Union[
    _FloatSetInput,
    _FloatDivideInput,
    _FloatMultiplyInput,
    _FloatIncrementInput,
    _FloatDecrementInput,
]
AtomicIntInput = Union[
    _IntSetInput,
    _IntDivideInput,
    _IntMultiplyInput,
    _IntIncrementInput,
    _IntDecrementInput,
]
AtomicBigIntInput = AtomicIntInput

class _StringListFilterEqualsInput(TypedDict):
    equals: Optional[List[_str]]


class _StringListFilterHasInput(TypedDict):
    has: _str


class _StringListFilterHasEveryInput(TypedDict):
    has_every: List[_str]


class _StringListFilterHasSomeInput(TypedDict):
    has_some: List[_str]


class _StringListFilterIsEmptyInput(TypedDict):
    is_empty: bool


StringListFilter = Union[
    _StringListFilterHasInput,
    _StringListFilterEqualsInput,
    _StringListFilterHasSomeInput,
    _StringListFilterIsEmptyInput,
    _StringListFilterHasEveryInput,
]


class _StringListUpdateSet(TypedDict):
    set: List[_str]


class _StringListUpdatePush(TypedDict):
    push: List[_str]


StringListUpdate = Union[
    List[_str],
    _StringListUpdateSet,
    _StringListUpdatePush,
]

class _BytesListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Base64']]


class _BytesListFilterHasInput(TypedDict):
    has: 'fields.Base64'


class _BytesListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Base64']


class _BytesListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Base64']


class _BytesListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BytesListFilter = Union[
    _BytesListFilterHasInput,
    _BytesListFilterEqualsInput,
    _BytesListFilterHasSomeInput,
    _BytesListFilterIsEmptyInput,
    _BytesListFilterHasEveryInput,
]


class _BytesListUpdateSet(TypedDict):
    set: List['fields.Base64']


class _BytesListUpdatePush(TypedDict):
    push: List['fields.Base64']


BytesListUpdate = Union[
    List['fields.Base64'],
    _BytesListUpdateSet,
    _BytesListUpdatePush,
]

class _DateTimeListFilterEqualsInput(TypedDict):
    equals: Optional[List[datetime.datetime]]


class _DateTimeListFilterHasInput(TypedDict):
    has: datetime.datetime


class _DateTimeListFilterHasEveryInput(TypedDict):
    has_every: List[datetime.datetime]


class _DateTimeListFilterHasSomeInput(TypedDict):
    has_some: List[datetime.datetime]


class _DateTimeListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DateTimeListFilter = Union[
    _DateTimeListFilterHasInput,
    _DateTimeListFilterEqualsInput,
    _DateTimeListFilterHasSomeInput,
    _DateTimeListFilterIsEmptyInput,
    _DateTimeListFilterHasEveryInput,
]


class _DateTimeListUpdateSet(TypedDict):
    set: List[datetime.datetime]


class _DateTimeListUpdatePush(TypedDict):
    push: List[datetime.datetime]


DateTimeListUpdate = Union[
    List[datetime.datetime],
    _DateTimeListUpdateSet,
    _DateTimeListUpdatePush,
]

class _BooleanListFilterEqualsInput(TypedDict):
    equals: Optional[List[_bool]]


class _BooleanListFilterHasInput(TypedDict):
    has: _bool


class _BooleanListFilterHasEveryInput(TypedDict):
    has_every: List[_bool]


class _BooleanListFilterHasSomeInput(TypedDict):
    has_some: List[_bool]


class _BooleanListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BooleanListFilter = Union[
    _BooleanListFilterHasInput,
    _BooleanListFilterEqualsInput,
    _BooleanListFilterHasSomeInput,
    _BooleanListFilterIsEmptyInput,
    _BooleanListFilterHasEveryInput,
]


class _BooleanListUpdateSet(TypedDict):
    set: List[_bool]


class _BooleanListUpdatePush(TypedDict):
    push: List[_bool]


BooleanListUpdate = Union[
    List[_bool],
    _BooleanListUpdateSet,
    _BooleanListUpdatePush,
]

class _IntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _IntListFilterHasInput(TypedDict):
    has: _int


class _IntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _IntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _IntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


IntListFilter = Union[
    _IntListFilterHasInput,
    _IntListFilterEqualsInput,
    _IntListFilterHasSomeInput,
    _IntListFilterIsEmptyInput,
    _IntListFilterHasEveryInput,
]


class _IntListUpdateSet(TypedDict):
    set: List[_int]


class _IntListUpdatePush(TypedDict):
    push: List[_int]


IntListUpdate = Union[
    List[_int],
    _IntListUpdateSet,
    _IntListUpdatePush,
]

class _BigIntListFilterEqualsInput(TypedDict):
    equals: Optional[List[_int]]


class _BigIntListFilterHasInput(TypedDict):
    has: _int


class _BigIntListFilterHasEveryInput(TypedDict):
    has_every: List[_int]


class _BigIntListFilterHasSomeInput(TypedDict):
    has_some: List[_int]


class _BigIntListFilterIsEmptyInput(TypedDict):
    is_empty: bool


BigIntListFilter = Union[
    _BigIntListFilterHasInput,
    _BigIntListFilterEqualsInput,
    _BigIntListFilterHasSomeInput,
    _BigIntListFilterIsEmptyInput,
    _BigIntListFilterHasEveryInput,
]


class _BigIntListUpdateSet(TypedDict):
    set: List[_int]


class _BigIntListUpdatePush(TypedDict):
    push: List[_int]


BigIntListUpdate = Union[
    List[_int],
    _BigIntListUpdateSet,
    _BigIntListUpdatePush,
]

class _FloatListFilterEqualsInput(TypedDict):
    equals: Optional[List[_float]]


class _FloatListFilterHasInput(TypedDict):
    has: _float


class _FloatListFilterHasEveryInput(TypedDict):
    has_every: List[_float]


class _FloatListFilterHasSomeInput(TypedDict):
    has_some: List[_float]


class _FloatListFilterIsEmptyInput(TypedDict):
    is_empty: bool


FloatListFilter = Union[
    _FloatListFilterHasInput,
    _FloatListFilterEqualsInput,
    _FloatListFilterHasSomeInput,
    _FloatListFilterIsEmptyInput,
    _FloatListFilterHasEveryInput,
]


class _FloatListUpdateSet(TypedDict):
    set: List[_float]


class _FloatListUpdatePush(TypedDict):
    push: List[_float]


FloatListUpdate = Union[
    List[_float],
    _FloatListUpdateSet,
    _FloatListUpdatePush,
]

class _JsonListFilterEqualsInput(TypedDict):
    equals: Optional[List['fields.Json']]


class _JsonListFilterHasInput(TypedDict):
    has: 'fields.Json'


class _JsonListFilterHasEveryInput(TypedDict):
    has_every: List['fields.Json']


class _JsonListFilterHasSomeInput(TypedDict):
    has_some: List['fields.Json']


class _JsonListFilterIsEmptyInput(TypedDict):
    is_empty: bool


JsonListFilter = Union[
    _JsonListFilterHasInput,
    _JsonListFilterEqualsInput,
    _JsonListFilterHasSomeInput,
    _JsonListFilterIsEmptyInput,
    _JsonListFilterHasEveryInput,
]


class _JsonListUpdateSet(TypedDict):
    set: List['fields.Json']


class _JsonListUpdatePush(TypedDict):
    push: List['fields.Json']


JsonListUpdate = Union[
    List['fields.Json'],
    _JsonListUpdateSet,
    _JsonListUpdatePush,
]

class _DecimalListFilterEqualsInput(TypedDict):
    equals: Optional[List[decimal.Decimal]]


class _DecimalListFilterHasInput(TypedDict):
    has: decimal.Decimal


class _DecimalListFilterHasEveryInput(TypedDict):
    has_every: List[decimal.Decimal]


class _DecimalListFilterHasSomeInput(TypedDict):
    has_some: List[decimal.Decimal]


class _DecimalListFilterIsEmptyInput(TypedDict):
    is_empty: bool


DecimalListFilter = Union[
    _DecimalListFilterHasInput,
    _DecimalListFilterEqualsInput,
    _DecimalListFilterHasSomeInput,
    _DecimalListFilterIsEmptyInput,
    _DecimalListFilterHasEveryInput,
]


class _DecimalListUpdateSet(TypedDict):
    set: List[decimal.Decimal]


class _DecimalListUpdatePush(TypedDict):
    push: List[decimal.Decimal]


DecimalListUpdate = Union[
    List[decimal.Decimal],
    _DecimalListUpdateSet,
    _DecimalListUpdatePush,
]


# IngestionLogs types

class IngestionLogsOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the IngestionLogs create method"""
    id: _int
    timestamp: datetime.datetime


class IngestionLogsCreateInput(IngestionLogsOptionalCreateInput):
    """Required arguments to the IngestionLogs create method"""
    job_id: _str
    log_type: _str
    message: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class IngestionLogsOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the IngestionLogs create method, without relations"""
    id: _int
    timestamp: datetime.datetime


class IngestionLogsCreateWithoutRelationsInput(IngestionLogsOptionalCreateWithoutRelationsInput):
    """Required arguments to the IngestionLogs create method, without relations"""
    job_id: _str
    log_type: _str
    message: _str

class IngestionLogsConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'IngestionLogsCreateWithoutRelationsInput'
    where: 'IngestionLogsWhereUniqueInput'

class IngestionLogsCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'IngestionLogsCreateWithoutRelationsInput'
    connect: 'IngestionLogsWhereUniqueInput'
    connect_or_create: 'IngestionLogsConnectOrCreateWithoutRelationsInput'


class IngestionLogsCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['IngestionLogsCreateWithoutRelationsInput', List['IngestionLogsCreateWithoutRelationsInput']]
    connect: Union['IngestionLogsWhereUniqueInput', List['IngestionLogsWhereUniqueInput']]
    connect_or_create: Union['IngestionLogsConnectOrCreateWithoutRelationsInput', List['IngestionLogsConnectOrCreateWithoutRelationsInput']]

_IngestionLogsWhereUnique_id_Input = TypedDict(
    '_IngestionLogsWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

IngestionLogsWhereUniqueInput = _IngestionLogsWhereUnique_id_Input


class IngestionLogsUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    job_id: _str
    log_type: _str
    message: _str
    timestamp: datetime.datetime


class IngestionLogsUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    job_id: _str
    log_type: _str
    message: _str
    timestamp: datetime.datetime


class IngestionLogsUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['IngestionLogsCreateWithoutRelationsInput']
    connect: List['IngestionLogsWhereUniqueInput']
    connect_or_create: List['IngestionLogsConnectOrCreateWithoutRelationsInput']
    set: List['IngestionLogsWhereUniqueInput']
    disconnect: List['IngestionLogsWhereUniqueInput']
    delete: List['IngestionLogsWhereUniqueInput']

    # TODO
    # update: List['IngestionLogsUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['IngestionLogsUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['IngestionLogsScalarWhereInput']
    # upsert: List['IngestionLogsUpserteWithWhereUniqueWithoutRelationsInput']


class IngestionLogsUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'IngestionLogsCreateWithoutRelationsInput'
    connect: 'IngestionLogsWhereUniqueInput'
    connect_or_create: 'IngestionLogsConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'IngestionLogsUpdateInput'
    # upsert: 'IngestionLogsUpsertWithoutRelationsInput'


class IngestionLogsUpsertInput(TypedDict):
    create: 'IngestionLogsCreateInput'
    update: 'IngestionLogsUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_IngestionLogs_id_OrderByInput = TypedDict(
    '_IngestionLogs_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_IngestionLogs_job_id_OrderByInput = TypedDict(
    '_IngestionLogs_job_id_OrderByInput',
    {
        'job_id': 'SortOrder',
    },
    total=True
)

_IngestionLogs_log_type_OrderByInput = TypedDict(
    '_IngestionLogs_log_type_OrderByInput',
    {
        'log_type': 'SortOrder',
    },
    total=True
)

_IngestionLogs_message_OrderByInput = TypedDict(
    '_IngestionLogs_message_OrderByInput',
    {
        'message': 'SortOrder',
    },
    total=True
)

_IngestionLogs_timestamp_OrderByInput = TypedDict(
    '_IngestionLogs_timestamp_OrderByInput',
    {
        'timestamp': 'SortOrder',
    },
    total=True
)

_IngestionLogs_RelevanceInner = TypedDict(
    '_IngestionLogs_RelevanceInner',
    {
        'fields': 'List[IngestionLogsScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_IngestionLogs_RelevanceOrderByInput = TypedDict(
    '_IngestionLogs_RelevanceOrderByInput',
    {
        '_relevance': '_IngestionLogs_RelevanceInner',
    },
    total=True
)

IngestionLogsOrderByInput = Union[
    '_IngestionLogs_id_OrderByInput',
    '_IngestionLogs_job_id_OrderByInput',
    '_IngestionLogs_log_type_OrderByInput',
    '_IngestionLogs_message_OrderByInput',
    '_IngestionLogs_timestamp_OrderByInput',
    '_IngestionLogs_RelevanceOrderByInput',
]



# recursive IngestionLogs types
# TODO: cleanup these types



IngestionLogsRelationFilter = TypedDict(
    'IngestionLogsRelationFilter',
    {
        'is': 'IngestionLogsWhereInput',
        'is_not': 'IngestionLogsWhereInput',
    },
    total=False,
)


class IngestionLogsListRelationFilter(TypedDict, total=False):
    some: 'IngestionLogsWhereInput'
    none: 'IngestionLogsWhereInput'
    every: 'IngestionLogsWhereInput'


class IngestionLogsInclude(TypedDict, total=False):
    """IngestionLogs relational arguments"""


class IngestionLogsIncludeFromIngestionLogs(TypedDict, total=False):
    """Relational arguments for IngestionLogs"""


class IngestionLogsArgsFromIngestionLogs(TypedDict, total=False):
    """Arguments for IngestionLogs"""
    include: 'IngestionLogsIncludeFromIngestionLogs'


class FindManyIngestionLogsArgsFromIngestionLogs(TypedDict, total=False):
    """Arguments for IngestionLogs"""
    take: int
    skip: int
    order_by: Union['IngestionLogsOrderByInput', List['IngestionLogsOrderByInput']]
    where: 'IngestionLogsWhereInput'
    cursor: 'IngestionLogsWhereUniqueInput'
    distinct: List['IngestionLogsScalarFieldKeys']
    include: 'IngestionLogsIncludeFromIngestionLogs'


class BankTransactionsIncludeFromIngestionLogs(TypedDict, total=False):
    """Relational arguments for IngestionLogs"""


class BankTransactionsArgsFromIngestionLogs(TypedDict, total=False):
    """Arguments for IngestionLogs"""
    include: 'BankTransactionsIncludeFromBankTransactions'


class FindManyBankTransactionsArgsFromIngestionLogs(TypedDict, total=False):
    """Arguments for IngestionLogs"""
    take: int
    skip: int
    order_by: Union['BankTransactionsOrderByInput', List['BankTransactionsOrderByInput']]
    where: 'BankTransactionsWhereInput'
    cursor: 'BankTransactionsWhereUniqueInput'
    distinct: List['BankTransactionsScalarFieldKeys']
    include: 'BankTransactionsIncludeFromBankTransactions'




FindManyIngestionLogsArgs = FindManyIngestionLogsArgsFromIngestionLogs
FindFirstIngestionLogsArgs = FindManyIngestionLogsArgsFromIngestionLogs


class IngestionLogsWhereInput(TypedDict, total=False):
    """IngestionLogs arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    job_id: Union[_str, 'types.StringFilter']
    log_type: Union[_str, 'types.StringFilter']
    message: Union[_str, 'types.StringFilter']
    timestamp: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['IngestionLogsWhereInput', List['IngestionLogsWhereInput']]
    # but this causes mypy to hang :/
    AND: List['IngestionLogsWhereInput']
    OR: List['IngestionLogsWhereInput']
    NOT: List['IngestionLogsWhereInput']



# aggregate IngestionLogs types


class IngestionLogsScalarWhereWithAggregatesInput(TypedDict, total=False):
    """IngestionLogs arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    job_id: Union[_str, 'types.StringWithAggregatesFilter']
    log_type: Union[_str, 'types.StringWithAggregatesFilter']
    message: Union[_str, 'types.StringWithAggregatesFilter']
    timestamp: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['IngestionLogsScalarWhereWithAggregatesInput']
    OR: List['IngestionLogsScalarWhereWithAggregatesInput']
    NOT: List['IngestionLogsScalarWhereWithAggregatesInput']



class IngestionLogsGroupByOutput(TypedDict, total=False):
    id: _int
    job_id: _str
    log_type: _str
    message: _str
    timestamp: datetime.datetime
    _sum: 'IngestionLogsSumAggregateOutput'
    _avg: 'IngestionLogsAvgAggregateOutput'
    _min: 'IngestionLogsMinAggregateOutput'
    _max: 'IngestionLogsMaxAggregateOutput'
    _count: 'IngestionLogsCountAggregateOutput'


class IngestionLogsAvgAggregateOutput(TypedDict, total=False):
    """IngestionLogs output for aggregating averages"""
    id: float


class IngestionLogsSumAggregateOutput(TypedDict, total=False):
    """IngestionLogs output for aggregating sums"""
    id: _int


class IngestionLogsScalarAggregateOutput(TypedDict, total=False):
    """IngestionLogs output including scalar fields"""
    id: _int
    job_id: _str
    log_type: _str
    message: _str
    timestamp: datetime.datetime


IngestionLogsMinAggregateOutput = IngestionLogsScalarAggregateOutput
IngestionLogsMaxAggregateOutput = IngestionLogsScalarAggregateOutput


class IngestionLogsMaxAggregateInput(TypedDict, total=False):
    """IngestionLogs input for aggregating by max"""
    id: bool
    job_id: bool
    log_type: bool
    message: bool
    timestamp: bool


class IngestionLogsMinAggregateInput(TypedDict, total=False):
    """IngestionLogs input for aggregating by min"""
    id: bool
    job_id: bool
    log_type: bool
    message: bool
    timestamp: bool


class IngestionLogsNumberAggregateInput(TypedDict, total=False):
    """IngestionLogs input for aggregating numbers"""
    id: bool


IngestionLogsAvgAggregateInput = IngestionLogsNumberAggregateInput
IngestionLogsSumAggregateInput = IngestionLogsNumberAggregateInput


IngestionLogsCountAggregateInput = TypedDict(
    'IngestionLogsCountAggregateInput',
    {
        'id': bool,
        'job_id': bool,
        'log_type': bool,
        'message': bool,
        'timestamp': bool,
        '_all': bool,
    },
    total=False,
)

IngestionLogsCountAggregateOutput = TypedDict(
    'IngestionLogsCountAggregateOutput',
    {
        'id': int,
        'job_id': int,
        'log_type': int,
        'message': int,
        'timestamp': int,
        '_all': int,
    },
    total=False,
)


IngestionLogsKeys = Literal[
    'id',
    'job_id',
    'log_type',
    'message',
    'timestamp',
]
IngestionLogsScalarFieldKeys = Literal[
    'id',
    'job_id',
    'log_type',
    'message',
    'timestamp',
]
IngestionLogsScalarFieldKeysT = TypeVar('IngestionLogsScalarFieldKeysT', bound=IngestionLogsScalarFieldKeys)

IngestionLogsRelationalFieldKeys = _NoneType

# BankTransactions types

class BankTransactionsOptionalCreateInput(TypedDict, total=False):
    """Optional arguments to the BankTransactions create method"""
    id: _int
    transaction_date: Optional[datetime.datetime]
    posting_date: Optional[datetime.datetime]
    raw_value_text: Optional[_str]
    raw_balance_text: Optional[_str]
    raw_json_data: Optional['fields.Json']
    created_at: datetime.datetime


class BankTransactionsCreateInput(BankTransactionsOptionalCreateInput):
    """Required arguments to the BankTransactions create method"""
    type: _str
    amount_decimal: decimal.Decimal
    raw_history_text: _str
    source_file_name: _str


# TODO: remove this in favour of without explicit relations
# e.g. PostCreateWithoutAuthorInput

class BankTransactionsOptionalCreateWithoutRelationsInput(TypedDict, total=False):
    """Optional arguments to the BankTransactions create method, without relations"""
    id: _int
    transaction_date: Optional[datetime.datetime]
    posting_date: Optional[datetime.datetime]
    raw_value_text: Optional[_str]
    raw_balance_text: Optional[_str]
    raw_json_data: Optional['fields.Json']
    created_at: datetime.datetime


class BankTransactionsCreateWithoutRelationsInput(BankTransactionsOptionalCreateWithoutRelationsInput):
    """Required arguments to the BankTransactions create method, without relations"""
    type: _str
    amount_decimal: decimal.Decimal
    raw_history_text: _str
    source_file_name: _str

class BankTransactionsConnectOrCreateWithoutRelationsInput(TypedDict):
    create: 'BankTransactionsCreateWithoutRelationsInput'
    where: 'BankTransactionsWhereUniqueInput'

class BankTransactionsCreateNestedWithoutRelationsInput(TypedDict, total=False):
    create: 'BankTransactionsCreateWithoutRelationsInput'
    connect: 'BankTransactionsWhereUniqueInput'
    connect_or_create: 'BankTransactionsConnectOrCreateWithoutRelationsInput'


class BankTransactionsCreateManyNestedWithoutRelationsInput(TypedDict, total=False):
    create: Union['BankTransactionsCreateWithoutRelationsInput', List['BankTransactionsCreateWithoutRelationsInput']]
    connect: Union['BankTransactionsWhereUniqueInput', List['BankTransactionsWhereUniqueInput']]
    connect_or_create: Union['BankTransactionsConnectOrCreateWithoutRelationsInput', List['BankTransactionsConnectOrCreateWithoutRelationsInput']]

_BankTransactionsWhereUnique_id_Input = TypedDict(
    '_BankTransactionsWhereUnique_id_Input',
    {
        'id': '_int',
    },
    total=True
)

BankTransactionsWhereUniqueInput = _BankTransactionsWhereUnique_id_Input


class BankTransactionsUpdateInput(TypedDict, total=False):
    """Optional arguments for updating a record"""
    id: Union[AtomicIntInput, _int]
    transaction_date: Optional[datetime.datetime]
    posting_date: Optional[datetime.datetime]
    type: _str
    amount_decimal: decimal.Decimal
    raw_history_text: _str
    raw_value_text: Optional[_str]
    raw_balance_text: Optional[_str]
    source_file_name: _str
    raw_json_data: Optional['fields.Json']
    created_at: datetime.datetime


class BankTransactionsUpdateManyMutationInput(TypedDict, total=False):
    """Arguments for updating many records"""
    id: Union[AtomicIntInput, _int]
    transaction_date: Optional[datetime.datetime]
    posting_date: Optional[datetime.datetime]
    type: _str
    amount_decimal: decimal.Decimal
    raw_history_text: _str
    raw_value_text: Optional[_str]
    raw_balance_text: Optional[_str]
    source_file_name: _str
    raw_json_data: Optional['fields.Json']
    created_at: datetime.datetime


class BankTransactionsUpdateManyWithoutRelationsInput(TypedDict, total=False):
    create: List['BankTransactionsCreateWithoutRelationsInput']
    connect: List['BankTransactionsWhereUniqueInput']
    connect_or_create: List['BankTransactionsConnectOrCreateWithoutRelationsInput']
    set: List['BankTransactionsWhereUniqueInput']
    disconnect: List['BankTransactionsWhereUniqueInput']
    delete: List['BankTransactionsWhereUniqueInput']

    # TODO
    # update: List['BankTransactionsUpdateWithWhereUniqueWithoutRelationsInput']
    # updateMany: List['BankTransactionsUpdateManyWithWhereUniqueWithoutRelationsInput']
    # deleteMany: List['BankTransactionsScalarWhereInput']
    # upsert: List['BankTransactionsUpserteWithWhereUniqueWithoutRelationsInput']


class BankTransactionsUpdateOneWithoutRelationsInput(TypedDict, total=False):
    create: 'BankTransactionsCreateWithoutRelationsInput'
    connect: 'BankTransactionsWhereUniqueInput'
    connect_or_create: 'BankTransactionsConnectOrCreateWithoutRelationsInput'
    disconnect: bool
    delete: bool

    # TODO
    # update: 'BankTransactionsUpdateInput'
    # upsert: 'BankTransactionsUpsertWithoutRelationsInput'


class BankTransactionsUpsertInput(TypedDict):
    create: 'BankTransactionsCreateInput'
    update: 'BankTransactionsUpdateInput'  # pyright: ignore[reportIncompatibleMethodOverride]


_BankTransactions_id_OrderByInput = TypedDict(
    '_BankTransactions_id_OrderByInput',
    {
        'id': 'SortOrder',
    },
    total=True
)

_BankTransactions_transaction_date_OrderByInput = TypedDict(
    '_BankTransactions_transaction_date_OrderByInput',
    {
        'transaction_date': 'SortOrder',
    },
    total=True
)

_BankTransactions_posting_date_OrderByInput = TypedDict(
    '_BankTransactions_posting_date_OrderByInput',
    {
        'posting_date': 'SortOrder',
    },
    total=True
)

_BankTransactions_type_OrderByInput = TypedDict(
    '_BankTransactions_type_OrderByInput',
    {
        'type': 'SortOrder',
    },
    total=True
)

_BankTransactions_amount_decimal_OrderByInput = TypedDict(
    '_BankTransactions_amount_decimal_OrderByInput',
    {
        'amount_decimal': 'SortOrder',
    },
    total=True
)

_BankTransactions_raw_history_text_OrderByInput = TypedDict(
    '_BankTransactions_raw_history_text_OrderByInput',
    {
        'raw_history_text': 'SortOrder',
    },
    total=True
)

_BankTransactions_raw_value_text_OrderByInput = TypedDict(
    '_BankTransactions_raw_value_text_OrderByInput',
    {
        'raw_value_text': 'SortOrder',
    },
    total=True
)

_BankTransactions_raw_balance_text_OrderByInput = TypedDict(
    '_BankTransactions_raw_balance_text_OrderByInput',
    {
        'raw_balance_text': 'SortOrder',
    },
    total=True
)

_BankTransactions_source_file_name_OrderByInput = TypedDict(
    '_BankTransactions_source_file_name_OrderByInput',
    {
        'source_file_name': 'SortOrder',
    },
    total=True
)

_BankTransactions_raw_json_data_OrderByInput = TypedDict(
    '_BankTransactions_raw_json_data_OrderByInput',
    {
        'raw_json_data': 'SortOrder',
    },
    total=True
)

_BankTransactions_created_at_OrderByInput = TypedDict(
    '_BankTransactions_created_at_OrderByInput',
    {
        'created_at': 'SortOrder',
    },
    total=True
)

_BankTransactions_RelevanceInner = TypedDict(
    '_BankTransactions_RelevanceInner',
    {
        'fields': 'List[BankTransactionsScalarFieldKeys]',
        'search': 'str',
        'sort': 'SortOrder',
    },
    total=True
)

_BankTransactions_RelevanceOrderByInput = TypedDict(
    '_BankTransactions_RelevanceOrderByInput',
    {
        '_relevance': '_BankTransactions_RelevanceInner',
    },
    total=True
)

BankTransactionsOrderByInput = Union[
    '_BankTransactions_id_OrderByInput',
    '_BankTransactions_transaction_date_OrderByInput',
    '_BankTransactions_posting_date_OrderByInput',
    '_BankTransactions_type_OrderByInput',
    '_BankTransactions_amount_decimal_OrderByInput',
    '_BankTransactions_raw_history_text_OrderByInput',
    '_BankTransactions_raw_value_text_OrderByInput',
    '_BankTransactions_raw_balance_text_OrderByInput',
    '_BankTransactions_source_file_name_OrderByInput',
    '_BankTransactions_raw_json_data_OrderByInput',
    '_BankTransactions_created_at_OrderByInput',
    '_BankTransactions_RelevanceOrderByInput',
]



# recursive BankTransactions types
# TODO: cleanup these types



BankTransactionsRelationFilter = TypedDict(
    'BankTransactionsRelationFilter',
    {
        'is': 'BankTransactionsWhereInput',
        'is_not': 'BankTransactionsWhereInput',
    },
    total=False,
)


class BankTransactionsListRelationFilter(TypedDict, total=False):
    some: 'BankTransactionsWhereInput'
    none: 'BankTransactionsWhereInput'
    every: 'BankTransactionsWhereInput'


class BankTransactionsInclude(TypedDict, total=False):
    """BankTransactions relational arguments"""


class IngestionLogsIncludeFromBankTransactions(TypedDict, total=False):
    """Relational arguments for BankTransactions"""


class IngestionLogsArgsFromBankTransactions(TypedDict, total=False):
    """Arguments for BankTransactions"""
    include: 'IngestionLogsIncludeFromIngestionLogs'


class FindManyIngestionLogsArgsFromBankTransactions(TypedDict, total=False):
    """Arguments for BankTransactions"""
    take: int
    skip: int
    order_by: Union['IngestionLogsOrderByInput', List['IngestionLogsOrderByInput']]
    where: 'IngestionLogsWhereInput'
    cursor: 'IngestionLogsWhereUniqueInput'
    distinct: List['IngestionLogsScalarFieldKeys']
    include: 'IngestionLogsIncludeFromIngestionLogs'


class BankTransactionsIncludeFromBankTransactions(TypedDict, total=False):
    """Relational arguments for BankTransactions"""


class BankTransactionsArgsFromBankTransactions(TypedDict, total=False):
    """Arguments for BankTransactions"""
    include: 'BankTransactionsIncludeFromBankTransactions'


class FindManyBankTransactionsArgsFromBankTransactions(TypedDict, total=False):
    """Arguments for BankTransactions"""
    take: int
    skip: int
    order_by: Union['BankTransactionsOrderByInput', List['BankTransactionsOrderByInput']]
    where: 'BankTransactionsWhereInput'
    cursor: 'BankTransactionsWhereUniqueInput'
    distinct: List['BankTransactionsScalarFieldKeys']
    include: 'BankTransactionsIncludeFromBankTransactions'




FindManyBankTransactionsArgs = FindManyBankTransactionsArgsFromBankTransactions
FindFirstBankTransactionsArgs = FindManyBankTransactionsArgsFromBankTransactions


class BankTransactionsWhereInput(TypedDict, total=False):
    """BankTransactions arguments for searching"""
    id: Union[_int, 'types.IntFilter']
    transaction_date: Union[None, datetime.datetime, 'types.DateTimeFilter']
    posting_date: Union[None, datetime.datetime, 'types.DateTimeFilter']
    type: Union[_str, 'types.StringFilter']
    amount_decimal: Union[decimal.Decimal, 'types.DecimalFilter']
    raw_history_text: Union[_str, 'types.StringFilter']
    raw_value_text: Union[None, _str, 'types.StringFilter']
    raw_balance_text: Union[None, _str, 'types.StringFilter']
    source_file_name: Union[_str, 'types.StringFilter']
    raw_json_data: Union[None, 'fields.Json', 'types.JsonFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeFilter']

    # should be noted that AND and NOT should be Union['BankTransactionsWhereInput', List['BankTransactionsWhereInput']]
    # but this causes mypy to hang :/
    AND: List['BankTransactionsWhereInput']
    OR: List['BankTransactionsWhereInput']
    NOT: List['BankTransactionsWhereInput']



# aggregate BankTransactions types


class BankTransactionsScalarWhereWithAggregatesInput(TypedDict, total=False):
    """BankTransactions arguments for searching"""
    id: Union[_int, 'types.IntWithAggregatesFilter']
    transaction_date: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    posting_date: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']
    type: Union[_str, 'types.StringWithAggregatesFilter']
    amount_decimal: Union[decimal.Decimal, 'types.DecimalWithAggregatesFilter']
    raw_history_text: Union[_str, 'types.StringWithAggregatesFilter']
    raw_value_text: Union[_str, 'types.StringWithAggregatesFilter']
    raw_balance_text: Union[_str, 'types.StringWithAggregatesFilter']
    source_file_name: Union[_str, 'types.StringWithAggregatesFilter']
    raw_json_data: Union['fields.Json', 'types.JsonWithAggregatesFilter']
    created_at: Union[datetime.datetime, 'types.DateTimeWithAggregatesFilter']

    AND: List['BankTransactionsScalarWhereWithAggregatesInput']
    OR: List['BankTransactionsScalarWhereWithAggregatesInput']
    NOT: List['BankTransactionsScalarWhereWithAggregatesInput']



class BankTransactionsGroupByOutput(TypedDict, total=False):
    id: _int
    transaction_date: datetime.datetime
    posting_date: datetime.datetime
    type: _str
    amount_decimal: decimal.Decimal
    raw_history_text: _str
    raw_value_text: _str
    raw_balance_text: _str
    source_file_name: _str
    raw_json_data: 'fields.Json'
    created_at: datetime.datetime
    _sum: 'BankTransactionsSumAggregateOutput'
    _avg: 'BankTransactionsAvgAggregateOutput'
    _min: 'BankTransactionsMinAggregateOutput'
    _max: 'BankTransactionsMaxAggregateOutput'
    _count: 'BankTransactionsCountAggregateOutput'


class BankTransactionsAvgAggregateOutput(TypedDict, total=False):
    """BankTransactions output for aggregating averages"""
    id: float


class BankTransactionsSumAggregateOutput(TypedDict, total=False):
    """BankTransactions output for aggregating sums"""
    id: _int


class BankTransactionsScalarAggregateOutput(TypedDict, total=False):
    """BankTransactions output including scalar fields"""
    id: _int
    transaction_date: datetime.datetime
    posting_date: datetime.datetime
    type: _str
    amount_decimal: decimal.Decimal
    raw_history_text: _str
    raw_value_text: _str
    raw_balance_text: _str
    source_file_name: _str
    raw_json_data: 'fields.Json'
    created_at: datetime.datetime


BankTransactionsMinAggregateOutput = BankTransactionsScalarAggregateOutput
BankTransactionsMaxAggregateOutput = BankTransactionsScalarAggregateOutput


class BankTransactionsMaxAggregateInput(TypedDict, total=False):
    """BankTransactions input for aggregating by max"""
    id: bool
    transaction_date: bool
    posting_date: bool
    type: bool
    amount_decimal: bool
    raw_history_text: bool
    raw_value_text: bool
    raw_balance_text: bool
    source_file_name: bool
    raw_json_data: bool
    created_at: bool


class BankTransactionsMinAggregateInput(TypedDict, total=False):
    """BankTransactions input for aggregating by min"""
    id: bool
    transaction_date: bool
    posting_date: bool
    type: bool
    amount_decimal: bool
    raw_history_text: bool
    raw_value_text: bool
    raw_balance_text: bool
    source_file_name: bool
    raw_json_data: bool
    created_at: bool


class BankTransactionsNumberAggregateInput(TypedDict, total=False):
    """BankTransactions input for aggregating numbers"""
    id: bool


BankTransactionsAvgAggregateInput = BankTransactionsNumberAggregateInput
BankTransactionsSumAggregateInput = BankTransactionsNumberAggregateInput


BankTransactionsCountAggregateInput = TypedDict(
    'BankTransactionsCountAggregateInput',
    {
        'id': bool,
        'transaction_date': bool,
        'posting_date': bool,
        'type': bool,
        'amount_decimal': bool,
        'raw_history_text': bool,
        'raw_value_text': bool,
        'raw_balance_text': bool,
        'source_file_name': bool,
        'raw_json_data': bool,
        'created_at': bool,
        '_all': bool,
    },
    total=False,
)

BankTransactionsCountAggregateOutput = TypedDict(
    'BankTransactionsCountAggregateOutput',
    {
        'id': int,
        'transaction_date': int,
        'posting_date': int,
        'type': int,
        'amount_decimal': int,
        'raw_history_text': int,
        'raw_value_text': int,
        'raw_balance_text': int,
        'source_file_name': int,
        'raw_json_data': int,
        'created_at': int,
        '_all': int,
    },
    total=False,
)


BankTransactionsKeys = Literal[
    'id',
    'transaction_date',
    'posting_date',
    'type',
    'amount_decimal',
    'raw_history_text',
    'raw_value_text',
    'raw_balance_text',
    'source_file_name',
    'raw_json_data',
    'created_at',
]
BankTransactionsScalarFieldKeys = Literal[
    'id',
    'transaction_date',
    'posting_date',
    'type',
    'amount_decimal',
    'raw_history_text',
    'raw_value_text',
    'raw_balance_text',
    'source_file_name',
    'raw_json_data',
    'created_at',
]
BankTransactionsScalarFieldKeysT = TypeVar('BankTransactionsScalarFieldKeysT', bound=BankTransactionsScalarFieldKeys)

BankTransactionsRelationalFieldKeys = _NoneType



# we have to import ourselves as types can be namespaced to types
from . import types, enums, models, fields